### ISSUE TITLE
Importing Logo, and LogoSection causes an Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by sb989** [codedthemes/mantis-free-react-admin-template#6] opened 2022-06-21 15:48 UTC
**Describe the bug**
I cloned the free version and got the Uncaught ReferenceError: process is not defined when importing components.

**To Reproduce**
1. yarn
2. yarn start
3. import Logo anywhere
4. get error

**Expected behavior**
No error

**Screenshots**

browser console output :
`The development server has disconnected.
Refresh the page if necessary. webpackHotDevClient.js:76
[HMR] Waiting for update signal from WDS... log.js:24
src/pages/dashboard/index.js
  Line 83:18:  Insert `·`  prettier/prettier

Search for the keywords to learn more about each error. index.js:1
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type". index.js:1
Uncaught ReferenceError: process is not defined
    4043 blank line 238378 > injectedScript:2
    r blank line 238378 > injectedScript:2
    8048 blank line 238378 > injectedScript:2
    r blank line 238378 > injectedScript:2
    8641 blank line 238378 > injectedScript:2
    r blank line 238378 > injectedScript:2
    <anonymous> blank line 238378 > injectedScript:2
    <anonymous> blank line 238378 > injectedScript:2
    <anonymous> blank line 238378 > injectedScript:2
    onload index.js:1
    be index.js:1
    de index.js:1
    handleErrors webpackHotDevClient.js:169
    onmessage webpackHotDevClient.js:213
    js webpackHotDevClient.js:195
    Webpack 7
blank line 238378 > injectedScript:2:13158
`
EDIT:
Upgrading react-scripts by doing yarn add react-scripts@latest fixes this error but breaks other things

**Comment by mohantechnology** [comment] 2022-08-01 12:25
the issue is due to one of the package "react-error-overlay" which is one of the  sub dependencies  of  react-scripts.
more information about issue "https://github.com/facebook/create-react-app/issues/11773". One of the solution is to update "react-error-overlay" to latest version or not used that  version which has this issue

solution using npm 
1) delete package-lock.json
2) add below code to package.json  `  "overrides": {
        "react-error-overlay": "6.0.9"
      }
}`
3) npm -f i 
4) restart the server

solution using yarn  can be found here
https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined/73192448#73192448

**Comment by phoenixcoded20** [comment] 2023-07-03 04:34
@sb989  this seems to old thread, but please close the issue if it resolve your problem.

**Closed** 2023-10-18 05:20 UTC
Labels: good first issue
